set -g default-terminal "screen-256color"

set-option -g prefix `
bind ` send-prefix

#setting the delay between prefix and command
set -s escape-time 5

# Set bind key to reload configuration file
bind r source-file ~/.config/tmux/tmux.conf \; display ​"Reloaded!"

# splitting panes with | and -
bind \\ split-window -h
bind - split-window -v

# remove confirmation when closing a pane or window
bind-key & kill-window
bind-key x kill-pane

# Enable mouse support
set -g mouse on
# set -ga terminal-overrides ',*256color*:smcup@:rmcup@'

# Set vi as the default editor
set -g status-keys vi

set-option -sa terminal-overrides 'xterm-256color:RGB'

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'mrjones2014/smart-splits.nvim'

# Plugin options.
set -g @smart-splits_no_wrap '' # to disable wrapping. (any value disables wrapping)
set -g @smart-splits_move_left_key  'C-Left' # key-mapping for navigation.
set -g @smart-splits_move_down_key  'C-Down' #  --"--
set -g @smart-splits_move_up_key    'C-Up' #  --"--
set -g @smart-splits_move_right_key 'C-Right' #  --"--
set -g @smart-splits_resize_left_key  'M-Left' # key-mapping for resizing.
set -g @smart-splits_resize_down_key  'M-Down' #  --"--
set -g @smart-splits_resize_up_key    'M-Up' #  --"--
set -g @smart-splits_resize_right_key 'M-Right' #  --"--
set -g @smart-splits_resize_step_size '3' # change the step-size for resizing.
set -g @tilish-navigator 'on'
set -g @resurrect-strategy-nvim 'session'

# Install `tpm` if needed.
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# press leader / to start tmux-sessionizer
bind-key -r \/ run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# Activate the plugins.
run '~/.config/tmux/plugins/tpm/tpm'
