# https://github.com/lpnh/fr.yazi
[[manager.prepend_keymap]]
on = ["f", "r"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[manager.prepend_keymap]]
on = ["f", "a"]
run = "plugin fr rga"
desc = "Search file by content (rga)"
# # Search by content using ripgrep
# #
# # This option uses ripgrep to output all the lines of all files, and then uses fzf to fuzzy matching.
#
# [[manager.prepend_keymap]]
# on   = [ "f","g" ]
# run  = "plugin fg"
# desc = "find file by content (fuzzy match)"
#
# # The following option passes the input to ripgrep for a match search, reusing the rg search each time the input is changed. This is useful for searching in large folders due to increased speed, but it does not support fuzzy matching.
#
# [[manager.prepend_keymap]]
# on   = [ "f","G" ]
# run  = "plugin fg --args='rg'"
# desc = "find file by content (ripgrep match)"
#
# # Search by content using ripgrep-all
# #
# # This option uses ripgrep-all to output all the lines of all files, and then uses fzf to fuzzy matching.
#
# [[manager.prepend_keymap]]
# on   = [ "f","a" ]
# run  = "plugin fg --args='rga'"
# desc = "find file by content (ripgrep-all)"
#
# # Search by filename with fzf
#
# [[manager.prepend_keymap]]
# on   = [ "f","f" ]
# run  = "plugin fg --args='fzf'"
# desc = "find file by filename"
